name: Curator
options:
  bundleIdPrefix: com.derryl
  deploymentTarget:
    tvOS: "17.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

configFiles:
  Debug: Curator/Config/Secrets.xcconfig
  Release: Curator/Config/Secrets.xcconfig

targets:
  Curator:
    type: application
    platform: tvOS
    deploymentTarget: "17.0"
    sources:
      - path: Curator
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: "YES"
        INFOPLIST_FILE: Curator/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.derryl.curator
        DEVELOPMENT_TEAM: M7B243E5V8
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: "App Icon & Top Shelf Image"
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        INFOPLIST_KEY_UIUserInterfaceStyle: Automatic
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
        Release:
          SWIFT_COMPILATION_MODE: wholemodule

  CuratorTests:
    type: bundle.unit-test
    platform: tvOS
    deploymentTarget: "17.0"
    sources:
      - path: CuratorTests
    dependencies:
      - target: Curator
    settings:
      base:
        GENERATE_INFOPLIST_FILE: "YES"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Curator.app/Curator"
        BUNDLE_LOADER: "$(TEST_HOST)"

  CuratorUITests:
    type: bundle.ui-testing
    platform: tvOS
    deploymentTarget: "17.0"
    sources:
      - path: CuratorUITests
    dependencies:
      - target: Curator
    settings:
      base:
        GENERATE_INFOPLIST_FILE: "YES"
        TEST_TARGET_NAME: Curator
